#json - javaScript object notation
#it is the computer and human readable format
#can be generated by one website and used by other website
#this code prints the json data from a website using python

import requests

res = requests.get("http://127.0.0.1:5000/api/flights/16")
data = res.json()
print(data["passengers"])
print(res.status_code)
